### ISSUE TITLE
Invalid python 3 modulo operator usage for byte string.

### ISSUE THREAD

**Issue by F483** [bmuller/rpcudp#7]
```
2016-01-16 14:42:22-0500 [-] Traceback (most recent call last):
2016-01-16 14:42:22-0500 [-]   File "example.py", line 28, in <module>
2016-01-16 14:42:22-0500 [-]     client.sayhi(('127.0.0.1', 1234), "Snake Plissken").addCallback(client.handleResult)
2016-01-16 14:42:22-0500 [-]   File "/home/f483/dev/upstream/rpcudp/rpcudp/protocol.py", line 99, in func
2016-01-16 14:42:22-0500 [-]     txdata = b'\x00%s%s' % (msgID, data)
2016-01-16 14:42:22-0500 [-] TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

**Comment by F483** [comment]
Fix at https://github.com/bmuller/rpcudp/pull/8

**Comment by bmuller** [comment]
I'm unable to reproduce this issue (with Python 3.5 or Python 2.7).  Can you provide some more specifics about your environment?  Thanks!

Btw - I split out the client/server components into an examples directory for ease of use.

**Comment by F483** [comment]
Test setup

```
$ git checkout 6482fbd53f5cfa8eeccda31557999a5fb389997b  # latest commit on master
HEAD ist jetzt bei 6482fbd... split out example into client/server files
$ python --version
Python 3.4.3
$ python setup.py install &> /dev/null
$ pip freeze
Twisted==15.5.0
future==0.15.2
rpcudp==2.0
u-msgpack-python==2.1
wheel==0.26.0
zope.interface==4.1.3
```

Running the example server

```
$ python example/server.py 
2016-01-18 10:53:32-0500 [-] Log opened.
2016-01-18 10:53:32-0500 [-] RPCServer starting on 1234
2016-01-18 10:53:32-0500 [-] Starting protocol <__main__.RPCServer object at 0x7f72063b3ba8>
```

Running the example client

```
$ python example/client.py 
2016-01-18 10:54:18-0500 [-] Log opened.
2016-01-18 10:54:18-0500 [-] RPCClient starting on 4567
2016-01-18 10:54:18-0500 [-] Starting protocol <__main__.RPCClient object at 0x7fb033a2d3c8>
2016-01-18 10:54:18-0500 [-] Traceback (most recent call last):
2016-01-18 10:54:18-0500 [-]   File "example/client.py", line 21, in <module>
2016-01-18 10:54:18-0500 [-]     client.sayhi(('127.0.0.1', 1234), "Snake Plissken").addCallback(client.handleResult)
2016-01-18 10:54:18-0500 [-]   File "/home/f483/dev/upstream/rpcudp/env/lib/python3.4/site-packages/rpcudp-2.0-py3.4.egg/rpcudp/protocol.py", line 94, in func
2016-01-18 10:54:18-0500 [-] TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

I also updated my pull request so that its merged with your new changes.

**Comment by HalfVoxel** [comment]
I think % formatting for bytes is only supported from python 3.5 and up. You are using python 3.4.3.

**Comment by bmuller** [comment]
I can reproduce now (thanks @HalfVoxel!).
